# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'download.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(390, 450)
        Frame.setMinimumSize(QtCore.QSize(390, 450))
        Frame.setMaximumSize(QtCore.QSize(600, 600))
        self.calendar_Widget = QtWidgets.QCalendarWidget(Frame)
        self.calendar_Widget.setGeometry(QtCore.QRect(10, 130, 361, 241))
        self.calendar_Widget.setObjectName("calendar_Widget")
        self.pushButton = QtWidgets.QPushButton(Frame)
        self.pushButton.setGeometry(QtCore.QRect(258, 400, 101, 41))
        self.pushButton.setStyleSheet("background-color: rgb(53, 132, 228);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 5px; \n"
"border: 2px solid rgb(224, 27, 36);")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Frame)
        self.calendar_Widget.clicked['QDate'].connect(self.calendar_Widget.showSelectedDate) # type: ignore
        self.calendar_Widget.currentPageChanged['int','int'].connect(Frame.update) # type: ignore
        self.calendar_Widget.clicked['QDate'].connect(self.pushButton.animateClick) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.pushButton.setText(_translate("Frame", "Confirm"))
        self.label.setText(_translate("Frame", "Download"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
